version = 1

test_patterns = ["/tests/**"]

exclude_patterns = [
    "/resources/**",
    "/.enterprise/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/rudderlabs/rudder-server"]
  dependencies_vendored = true